### ISSUE TITLE
Error:Unknown HTTP status code: default

### ISSUE THREAD

**Issue by sigmasoldi3r** [guardrail-dev/sbt-guardrail#114] opened 2021-07-13 08:06 UTC
While attempting to reproduce the minimal example with `petstore.yaml` from swagger, the process crashes:

```
Warning: Tried to extract the base path for relative glob petstore.yaml/**/*. To disable this warning, re-run the program with java option, -Dsbt.io.implicit.relative.glob.conversion=allow
Warning: Using `tags` to define package membership is deprecated in favor of the `x-jvm-package` vendor extension (.paths./pets.operations.GET.tags)
Warning: Using `tags` to define package membership is deprecated in favor of the `x-jvm-package` vendor extension (.paths./pets.operations.POST.tags)
Warning: Using `tags` to define package membership is deprecated in favor of the `x-jvm-package` vendor extension (.paths./pets/{petId}.operations.GET.tags)
Error:Unknown HTTP status code: default
[error] (Compile / guardrail) com.twilio.guardrail.sbt.CodegenFailedException
[error] Total time: 1 s, completed 13 Jul 2021, 10:03:57
```

My config is:

```sbt
guardrailTasks in Compile := List(
  ScalaClient(
    specPath = file("petstore.yaml"),
    pkg = "com.argochamber.eventual.api"
  )
)
```

**Comment by kelnos** [comment] 2021-07-13 09:56
Dupe of https://github.com/guardrail-dev/guardrail/issues/96

**Comment by blast-hardcheese** [comment] 2022-02-26 17:55
Closing due to duplicate

**Closed by blast-hardcheese** 2022-02-26 17:55 UTC
Labels: duplicate
